Repository dzikoysk/reposilite, pull requests merged in 2023-09, with the labels that each got.

#1926 GH-1926 Fix tinylog file size policy
  reposilite-backend/src/main/resources/tinylog.properties
Labels: bug

#1934 GH-1934 Check if user/group already exist in entrypoint.sh
  entrypoint.sh
Labels: enhancement, distribution

#1941 GH-1939 Improve Apache guide
  reposilite-site/data/guides/integrations/apache.md
Labels: documentation
